
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Yakumo_ko", email = "2501390802@qq.com"},
]
dependencies = [
    "bs4>=0.0.1",
    "lxml>=4.9.3",
    "pydantic>=2.1.1",
    "httpx>=0.24.1",
]
requires-python = ">=3.8"
license = {text = "MIT"}

